### ISSUE TITLE
API CORS missing header

### ISSUE THREAD

**Issue by mberacochea** [EBI-Metagenomics/ebi-metagenomics-webkit#18]
Hi,
I'm trying to use this library but the API is not working as expected. 
CORS doesn't appear to be enabled for requests [from any origin](https://emg-docs.readthedocs.io/en/latest/api.html?highlight=cors#cross-origin-resource-sharing). The examples of the [documentation](https://emg-docs.readthedocs.io/en/latest/npm-package.html) work as CORS seems to be on for the domain `https://fiddle.jshell.net`.

```curl
curl -I "https://www.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: https://fiddle.jshell.net" -H "Origin: https://fiddle.jshell.net"
HTTP/1.1 200 OK
Server: nginx/1.12.2
Vary: Accept, Origin, Cookie
Content-Type: application/json
Strict-Transport-Security: max-age=0
Date: Sat, 23 Mar 2019 18:40:46 GMT
x-xss-protection: 1; mode=block
Access-Control-Allow-Origin: https://fiddle.jshell.net
x-content-type-options: nosniff
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Allow: GET, HEAD, OPTIONS
Content-Length: 1536
```
But for other domains the header `Access-Control-Allow-Origin` is missing.

Examples:

Fake domain: `https://fiddle.jshell.com`

```curl
curl -I "https://www.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: https://fiddle.jshell.com" -H "Origin: https://fiddle.jshell.com"
HTTP/1.1 200 OK
Server: nginx/1.12.2
Vary: Accept, Origin, Cookie
Content-Type: application/json
Strict-Transport-Security: max-age=0
Date: Sat, 23 Mar 2019 18:43:12 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Allow: GET, HEAD, OPTIONS
Content-Length: 1536
```

Fake domain: `http://mgnify.local:8080`

```curl
curl -I "https://www.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: http://mgnify.local:8080" -H "Origin: http://mgnify.local:8080"
HTTP/1.1 200 OK
Server: nginx/1.12.2
Vary: Accept, Origin, Cookie
Content-Type: application/json
Strict-Transport-Security: max-age=0
Date: Sat, 23 Mar 2019 18:52:17 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Allow: GET, HEAD, OPTIONS
Content-Length: 1536
```

I'm not sure if this is the right place to report this issue, if not could please point me in the right direction?

Regards

**Comment by mb1069** [comment]
Hello Martín,
Thank you for reaching out (This is indeed the right place for this).
We currently only allow cross origin requests from whitelisted domains, which you can request via email to metagenomics-help@ebi.ac.uk. 
In the mean time, you can always used our dev site for development purposes [()](https://wwwdev.ebi.ac.uk/metagenomics/api/v1/) which I believe should work with the npm package above. Do let me know if this is not the case,
Kindest,
Miguel Boland
Software engineer
Metagenomics Team, Protein families
EMBL-EBI

**Comment by mberacochea** [comment]
Hi Miguel,

Thank you for your response. I think that `wwwdev` is not working either, this is the response for a quicl test using `curl`.

```curl
~> curl -I "https://wwwdev.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: https://fiddle.jshell.com" -H "Origin: https://fiddle.jshell.com"
HTTP/2 200
server: nginx/1.12.2
vary: Accept, Origin, Cookie
content-type: application/json
date: Mon, 25 Mar 2019 13:23:22 GMT
x-xss-protection: 1; mode=block
accept-ranges: bytes
x-content-type-options: nosniff
allow: GET, HEAD, OPTIONS
x-frame-options: SAMEORIGIN
x-cache-info: caching
content-length: 1560

~> curl -I "https://wwwdev.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: https://fiddle.jshell.net" -H "Origin: https://fiddle.jshell.cnet"
HTTP/2 200
server: nginx/1.12.2
vary: Accept, Origin, Cookie
content-type: application/json
date: Mon, 25 Mar 2019 13:23:39 GMT
x-xss-protection: 1; mode=block
accept-ranges: bytes
x-content-type-options: nosniff
allow: GET, HEAD, OPTIONS
x-frame-options: SAMEORIGIN
x-cache-info: caching
content-length: 1560

~> curl -I "https://wwwdev.ebi.ac.uk/metagenomics/api/v1/studies/ERP001736" -H "Accept: application/json" -H "Referer: https://wwwdev.ebi.ac.uk" -H "Origin: https://wwwdev.ebi.ac.uk"
HTTP/2 200
server: nginx/1.12.2
vary: Accept, Origin, Cookie
content-type: application/json
date: Mon, 25 Mar 2019 13:24:07 GMT
x-xss-protection: 1; mode=block
access-control-allow-origin: https://wwwdev.ebi.ac.uk
accept-ranges: bytes
x-content-type-options: nosniff
allow: GET, HEAD, OPTIONS
x-frame-options: SAMEORIGIN
x-cache-info: caching
content-length: 1560
```

Kind regards

**Comment by mberacochea** [comment]
Hi @mb1069 ,

CORs is not enabled for either site. Anyway, using a browser extension to disable the CORS, I was able to build this little example https://mberacochea.github.io/ebi-metagenomics-webkit-example/. Kudos for the library.

Regards,
Martin

**Comment by mb1069** [comment]
For future reference; if you would like to build this library into your systems, please contact the metagenomics helpdesk (metagenomics-help@ebi.ac.uk) with your query so we can provide you access through the CORS config.

**Comment by mberacochea** [comment]
Excellent. Thank you!
