### ISSUE TITLE
Migrate Codacy from Miguel's account to one managed by the Microbiome Informatics team

### ISSUE THREAD

**Issue by mberacochea** [EBI-Metagenomics/ebi-metagenomics-webkit#43]

**Comment by mb1069** [comment]
Hey Martin, is this a github or email @ ebi.ac.uk account? I've checked if my personal gmail or github account are linked and found no known repositories in codacy.

**Comment by mberacochea** [comment]
Hey Miguel, the badge at least -> https://app.codacy.com/manual/mb1069/ebi-metagenomics-webkit. I assumed that mb1069 was you, but that url doesn't work.

**Comment by mb1069** [comment]
Aha found it, we had setup a MGnify organisation.
I've added your email (mbc@ebi.ac.uk) to it, let me know if that solves the issue?

**Comment by mberacochea** [comment]
Nice, thank you!. I'll check the configuration later.
